version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security:
        dependency-type: "production"
        applies-to: security-updates
      dependencies:
        dependency-type: "production"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates

