#!/bin/sh

# GIT PRE-COMMIT HOOK (copy to .git/hooks)
# ----------------------------------------
#
# - checks all changed files for PSR-2 compatibility
#   and aborts if any file doesn't comply
# - checks code for code coverage and prints a warning
#   if it is not within the threshold (but doesn't aborts)

# check style of changed files
PHP_CS_FIXER_IGNORE_ENV=true php -n vendor/bin/php-cs-fixer fix src --dry-run --rules=@PSR2 --verbose || exit 1;

echo
echo "Running QA ..."
# code coverage will only be checked, but won't stop the commit
# (it will stop pushes)
bin/qa
echo

exit 0
