name: aaronjewell/dephpend
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: shivammathur/setup-php@2.29.0
      with:
        tools: phpunit
        php-version: "${{ matrix.php }}"
    - run: mkdir -p build/logs
    - run: composer validate --strict
    - run: composer install --prefer-dist
    - run: bin/check-code-cov
    - run: vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover ./build/logs/clover.xml
    - run: wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.2/php-coveralls.phar
    - run: php php-coveralls.phar -v
    strategy:
      matrix:
        php:
        - '8.4'
        - '8.3'
        - '8.2'
        - '8.1'
        - '8.0'
        - '7.4'
        - '7.3'
        - '7.2'
